name: Sync Branches after Production Merge

on:
  push:
    branches:
      - production

jobs:
  sync_branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync homolog with production
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          source_branch: "production"
          destination_branch: "homolog"
          github_token: ${{ secrets.ACTIONS_PAT }}

      - name: Sync develop with production
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          source_branch: "production"
          destination_branch: "develop"
          github_token: ${{ secrets.ACTIONS_PAT }}
